apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    app: istio-ingressgateway
    install.operator.istio.io/owning-resource: installed-state
    install.operator.istio.io/owning-resource-namespace: istio-system
    istio: ingressgateway
    operator.istio.io/component: IngressGateways
    operator.istio.io/managed: Reconcile
    operator.istio.io/version: 1.6.5
    release: istio
  name: istio-ingressgateway
  namespace: istio-system
  resourceVersion: "3623549"
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: status-port
    nodePort: 30519
    port: 15020
    protocol: TCP
    targetPort: 15020
  - name: http2
    nodePort: 31984
    port: 80
    protocol: TCP
    targetPort: 8080
  - name: https
    nodePort: 30475
    port: 443
    protocol: TCP
    targetPort: 8443
  - name: tcp
    nodePort: 31381
    port: 31400
    protocol: TCP
    targetPort: 31400
  - name: tls
    nodePort: 31223
    port: 15443
    protocol: TCP
    targetPort: 15443
  selector:
    app: istio-ingressgateway
    istio: ingressgateway
  sessionAffinity: None
  type: NodePort 
